import type { CategoryId, L, Lang, Pack, Product, QuizQuestion } from "./types";
import { CATEGORIES } from "./categories";
import { BROCHURES } from "./brochures";
import { FEED_ADDITIVES } from "./products/feed-additives";
import { NUTRITION } from "./products/nutrition";
import { HERBAL_BIOSECURITY } from "./products/herbal-biosecurity";
import { MEDICINES } from "./products/medicines";
import SHEETS from "./sheets.json";
import { TECHNICAL } from "./technical";
import { FOUNDATIONS } from "./foundations";
import { GLOSSARY, type Term } from "./glossary";

export * from "./types";
export { CATEGORIES, BROCHURES, TECHNICAL, FOUNDATIONS, GLOSSARY };
export type { Term };

const categoryOrder = new Map(CATEGORIES.map((c, i) => [c.id, i]));

/** Every product, in product-manual order (category, then as listed). */
export const PRODUCTS: Product[] = [...FEED_ADDITIVES, ...NUTRITION, ...HERBAL_BIOSECURITY, ...MEDICINES].sort(
  (a, b) => (categoryOrder.get(a.category) ?? 0) - (categoryOrder.get(b.category) ?? 0),
);

const bySlug = new Map(PRODUCTS.map((p) => [p.slug, p]));

export function getProduct(slug: string): Product | undefined {
  return bySlug.get(slug);
}

export function getCategory(id: CategoryId) {
  return CATEGORIES.find((c) => c.id === id)!;
}

export function productsIn(category: CategoryId): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function t(text: L, lang: Lang): string {
  return text[lang];
}

// --- Technical learning ------------------------------------------------------

/** All English text of a product, for matching glossary terms. */
function productText(p: Product): string {
  return [
    p.name,
    p.tagline.en,
    ...p.composition,
    ...p.benefits.en,
    ...p.dosage.en,
    p.learn.problem.en,
    p.learn.how.en,
    p.learn.pitch.en,
    p.learn.proof?.en ?? "",
    ...(TECHNICAL[p.slug]?.en ?? []),
    // Every medicine lesson should teach the withdrawal period.
    p.rx ? "withdrawal" : "",
  ].join(" \n ");
}

/** Glossary terms used in this product's lesson, in glossary order. */
export function termsFor(p: Product, limit = 8): Term[] {
  const text = productText(p);
  return GLOSSARY.filter((term) =>
    term.match.some((src) => {
      // Acronym patterns (with \b and capitals) are case-sensitive; plain
      // words match in any case.
      const caseSensitive = /\\b/.test(src) && /[A-Z]{2}/.test(src);
      return new RegExp(src, caseSensitive ? "" : "i").test(text);
    }),
  ).slice(0, limit);
}

export function formatPack(pack: Pack): string {
  return `${pack.size} ${pack.unit}`;
}

export function formatPacks(packs: Pack[]): string {
  return packs.map((p) => (p.label ? `${formatPack(p)} (${p.label})` : formatPack(p))).join(", ");
}

// --- Shareable PDF sheets --------------------------------------------------
// Files are generated by scripts/split-brochures.py from lib/catalog/sheets.json.

type SheetEntry = {
  summary: { page: number; half: "top" | "bottom" };
  detail?: { brochure: string; pages: number[] };
};
const sheets = SHEETS as Record<string, SheetEntry>;

export type ProductSheet = {
  /** "detail" = the product's pages from its range brochure;
   * "summary" = its one-page entry from the product manual. */
  kind: "detail" | "summary";
  file: string;
  pages: number;
  brochureTitle: L;
};

export function productSheets(slug: string): ProductSheet[] {
  const entry = sheets[slug];
  if (!entry) return [];
  const manual = BROCHURES.find((b) => b.id === "product-manual")!;
  const out: ProductSheet[] = [];
  if (entry.detail) {
    const brochure = BROCHURES.find((b) => b.id === entry.detail!.brochure)!;
    out.push({ kind: "detail", file: `/docs/products/${slug}.pdf`, pages: entry.detail.pages.length, brochureTitle: brochure.title });
  }
  out.push({ kind: "summary", file: `/docs/products/${slug}-summary.pdf`, pages: 1, brochureTitle: manual.title });
  return out;
}

/** The sheet to share by default: the detailed one when there is one. */
export function primarySheet(slug: string): ProductSheet | undefined {
  return productSheets(slug)[0];
}

/** Which full brochures a product appears in (always includes the manual). */
export function brochuresFor(slug: string) {
  const entry = sheets[slug];
  return BROCHURES.filter((b) => b.id === "product-manual" || b.id === entry?.detail?.brochure);
}

// --- Quiz ------------------------------------------------------------------
// Five questions (when to use, product group, dose, packs, composition) are
// generated from the product data itself, so every answer is
// right by construction and the quiz stays in sync when a product changes.
// Shuffling is seeded by the product slug, so the server-rendered page and
// the client agree on the option order.

function hash(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function seeded(seed: number) {
  let x = seed || 1;
  return () => {
    x ^= x << 13;
    x ^= x >>> 17;
    x ^= x << 5;
    return (x >>> 0) / 4294967296;
  };
}

function shuffle<T>(items: T[], seed: string): T[] {
  const rand = seeded(hash(seed));
  const out = [...items];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

/** Pick `n` distinct distractors (by English text) that differ from `correct`. */
function distractors(correct: L, pool: L[], n: number, seed: string): L[] {
  const seen = new Set([correct.en]);
  const out: L[] = [];
  for (const item of shuffle(pool, seed)) {
    if (seen.has(item.en)) continue;
    seen.add(item.en);
    out.push(item);
    if (out.length === n) break;
  }
  return out;
}

function question(id: string, q: L, correct: L, wrong: L[]): QuizQuestion {
  const options = shuffle([correct, ...wrong], id);
  return { id, q, options, answer: options.indexOf(correct) };
}

const firstDose = (p: Product): L => ({ en: p.dosage.en[0], hi: p.dosage.hi[0] });
const packsText = (p: Product): L => ({ en: formatPacks(p.packs), hi: formatPacks(p.packs) });

export function quizFor(product: Product): QuizQuestion[] {
  const others = PRODUCTS.filter((p) => p.slug !== product.slug);
  const otherCategories = others.filter((p) => p.category !== product.category);
  const sameForm = others.filter((p) => p.form === product.form);
  const s = product.slug;

  const questions: QuizQuestion[] = [
    question(
      `${s}:problem`,
      {
        en: `When should you recommend ${product.name}?`,
        hi: `${product.name} की सलाह कब देनी चाहिए?`,
      },
      product.learn.problem,
      distractors(product.learn.problem, otherCategories.map((p) => p.learn.problem), 2, `${s}:problem`),
    ),
    question(
      `${s}:category`,
      { en: `${product.name} belongs to which product group?`, hi: `${product.name} किस प्रोडक्ट ग्रुप का है?` },
      getCategory(product.category).name,
      distractors(
        getCategory(product.category).name,
        CATEGORIES.filter((c) => c.id !== product.category).map((c) => c.name),
        2,
        `${s}:category`,
      ),
    ),
    question(
      `${s}:dose`,
      { en: `What is the recommended dose of ${product.name}?`, hi: `${product.name} की सही डोज़ क्या है?` },
      firstDose(product),
      distractors(firstDose(product), (sameForm.length >= 2 ? sameForm : others).map(firstDose), 2, `${s}:dose`),
    ),
    question(
      `${s}:packs`,
      { en: `Which pack sizes does ${product.name} come in?`, hi: `${product.name} किन पैक साइज़ में आता है?` },
      packsText(product),
      distractors(packsText(product), others.map(packsText), 2, `${s}:packs`),
    ),
    question(
      `${s}:active`,
      {
        en: `Which of these is part of the composition of ${product.name}?`,
        hi: `इनमें से कौन ${product.name} की संरचना (composition) का हिस्सा है?`,
      },
      keyActive(product),
      distractors(keyActive(product), otherCategories.map(keyActive), 2, `${s}:active`),
    ),
  ];
  return questions;
}

/** The first real ingredient line of a product's composition (skipping
 * headers like "Each kg contains:"). Ingredient names are the same in both
 * languages. */
function keyActive(p: Product): L {
  const line = p.composition.find((c) => !/:\s*$/.test(c) && !/^(each|minimum|composition)/i.test(c)) ?? p.composition[0];
  return { en: line, hi: line };
}

/** A lesson counts as passed at this many correct answers out of five. */
export const PASS_MARK = 4;
