import {
  LayoutDashboard,
  Users,
  MapPin,
  Package,
  Calendar,
  Car,
  Target,
  Receipt,
  Wallet,
  FlaskConical,
  Binoculars,
  BookOpen,
  BarChart3,
  Menu,
  LogOut,
  Plus,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Check,
  Clock,
  Truck,
  Box,
  Map,
  IndianRupee,
  Navigation,
  Pencil,
  X,
  Tags,
  UserCog,
  Flower2,
  Compass,
  Share2,
  Beaker,
  Zap,
  Droplets,
  Shield,
  Sprout,
  Gem,
  Egg,
  Thermometer,
  TrendingUp,
  HeartPulse,
  Leaf,
  Bug,
  ShieldPlus,
  Pill,
  ThermometerSun,
  Sun,
  ShieldCheck,
  Syringe,
  GraduationCap,
  Library,
  Download,
  Search,
  Languages,
  Award,
  CircleCheck,
  FileText,
  ExternalLink,
  Lightbulb,
  Quote,
  TriangleAlert,
  RefreshCw,
  Layers,
  Trophy,
  MessageCircle,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  users: Users,
  "map-pin": MapPin,
  package: Package,
  calendar: Calendar,
  car: Car,
  target: Target,
  receipt: Receipt,
  wallet: Wallet,
  "flask-conical": FlaskConical,
  binoculars: Binoculars,
  "book-open": BookOpen,
  "bar-chart-3": BarChart3,
  menu: Menu,
  "log-out": LogOut,
  plus: Plus,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  check: Check,
  clock: Clock,
  truck: Truck,
  box: Box,
  map: Map,
  "indian-rupee": IndianRupee,
  navigation: Navigation,
  edit: Pencil,
  x: X,
  tags: Tags,
  "user-cog": UserCog,
  flower: Flower2,
  compass: Compass,
  share: Share2,
  "beaker": Beaker,
  "zap": Zap,
  "droplets": Droplets,
  "shield": Shield,
  "sprout": Sprout,
  "gem": Gem,
  "egg": Egg,
  "thermometer": Thermometer,
  "trending-up": TrendingUp,
  "heart-pulse": HeartPulse,
  "leaf": Leaf,
  "bug": Bug,
  "shield-plus": ShieldPlus,
  "pill": Pill,
  "thermometer-sun": ThermometerSun,
  "sun": Sun,
  "shield-check": ShieldCheck,
  "syringe": Syringe,
  "graduation-cap": GraduationCap,
  "library": Library,
  "download": Download,
  "search": Search,
  "languages": Languages,
  "award": Award,
  "circle-check": CircleCheck,
  "file-text": FileText,
  "external-link": ExternalLink,
  "lightbulb": Lightbulb,
  "quote": Quote,
  "triangle-alert": TriangleAlert,
  "refresh-cw": RefreshCw,
  "layers": Layers,
  "trophy": Trophy,
  "message-circle": MessageCircle,
};

export function Icon({
  name,
  className,
  size = 18,
}: {
  name: string;
  className?: string;
  size?: number;
}) {
  const Cmp = MAP[name] ?? Package;
  return <Cmp className={className} size={size} strokeWidth={2} />;
}
